import { Exam, StaffMember, ExamHall, Device, ProblemIncident } from './types';

export const INITIAL_EXAMS: Exam[] = [
  {
    id: 'ex-1',
    exam: 'Mathematics',
    subjectCode: 'MATH-301',
    date: 'Tue, 27 May 2025',
    time: '09:00 – 11:00',
    startTime: '09:00',
    endTime: '11:00',
    duration: '2 Hours',
    session: 'Morning (09:00 - 11:00)',
    hall: 'A1-01',
    block: 'A1',
    floor: '1',
    staff: 'Mr. James Lewis',
    staffId: 'st-1',
    teacher: 'Mr. James Lewis',
    backupTeacher: 'Ms. Sarah Carter',
    requiredInvigilators: 1,
    status: 'Ready',
    notes: 'Standard exam setup.\nNo special requirements.',
    paperDistributionMinutesBefore: 15,
  },
  {
    id: 'ex-2',
    exam: 'Physics',
    subjectCode: 'PHY-202',
    date: 'Tue, 27 May 2025',
    time: '09:00 – 11:00',
    startTime: '09:00',
    endTime: '11:00',
    duration: '2 Hours',
    session: 'Morning (09:00 - 11:00)',
    hall: 'A1-02',
    block: 'A1',
    floor: '1',
    staff: 'Ms. Sarah Khan',
    staffId: 'st-2',
    teacher: 'Ms. Sarah Khan',
    backupTeacher: 'Mr. David Clark',
    requiredInvigilators: 1,
    status: 'Ready',
    notes: 'Formula sheets provided at entrance.\nScientific calculators permitted.',
    paperDistributionMinutesBefore: 15,
  },
  {
    id: 'ex-3',
    exam: 'Chemistry',
    subjectCode: 'CHEM-205',
    date: 'Tue, 27 May 2025',
    time: '13:00 – 15:00',
    startTime: '13:00',
    endTime: '15:00',
    duration: '2 Hours',
    session: 'Afternoon (13:00 - 15:00)',
    hall: 'A1-03',
    block: 'A1',
    floor: '1',
    staff: 'Mr. Ravi Patel',
    staffId: 'st-3',
    teacher: 'Mr. Ravi Patel',
    backupTeacher: 'Ms. Clara Wilson',
    requiredInvigilators: 1,
    status: 'Late',
    notes: 'Staff delayed in transit.\nReliever notified and on standby.',
    paperDistributionMinutesBefore: 15,
  },
  {
    id: 'ex-4',
    exam: 'Biology',
    subjectCode: 'BIO-101',
    date: 'Tue, 27 May 2025',
    time: '13:00 – 15:00',
    startTime: '13:00',
    endTime: '15:00',
    duration: '2 Hours',
    session: 'Afternoon (13:00 - 15:00)',
    hall: 'A1-04',
    block: 'A1',
    floor: '1',
    staff: 'Ms. Emily Green',
    staffId: 'st-4',
    teacher: 'Ms. Emily Green',
    backupTeacher: 'Mr. Thomas Evans',
    requiredInvigilators: 1,
    status: 'Changed',
    notes: 'Specimen diagram sheets distributed.\nDesks sanitized and numbered.',
    paperDistributionMinutesBefore: 15,
  },
  {
    id: 'ex-5',
    exam: 'History',
    subjectCode: 'HIST-104',
    date: 'Tue, 27 May 2025',
    time: '16:00 – 18:00',
    startTime: '16:00',
    endTime: '18:00',
    duration: '2 Hours',
    session: 'Evening (16:00 - 18:00)',
    hall: 'B2-02',
    block: 'B2',
    floor: '2',
    staff: 'Mr. Ahmed Ali',
    staffId: 'st-5',
    teacher: 'Mr. Ahmed Ali',
    backupTeacher: 'Ms. Taylor Brooks',
    requiredInvigilators: 1,
    status: 'Ready',
    notes: 'Room verified. Clean desk protocol enforced.',
    paperDistributionMinutesBefore: 15,
  },
  {
    id: 'ex-6',
    exam: 'English',
    subjectCode: 'ENG-201',
    date: 'Tue, 27 May 2025',
    time: '16:00 – 18:00',
    startTime: '16:00',
    endTime: '18:00',
    duration: '2 Hours',
    session: 'Evening (16:00 - 18:00)',
    hall: 'B2-03',
    block: 'B2',
    floor: '2',
    staff: 'Ms. Aisha Rahman',
    staffId: 'st-6',
    teacher: 'Ms. Aisha Rahman',
    backupTeacher: 'Mr. David Clark',
    requiredInvigilators: 1,
    status: 'Ready',
    notes: 'Answer booklets pre-allocated.\n10 min reading time before writing.',
    paperDistributionMinutesBefore: 15,
  },
];

export const INITIAL_HALLS: ExamHall[] = [
  {
    id: 'h-1',
    hall: 'A1-01',
    block: 'A1',
    floor: '01',
    capacity: 40,
    currentExam: 'Mathematics',
    faculty: 'Mr. James Lewis',
    beaconId: 'B-1042',
    beaconStatus: 'Detected',
    deviceStatus: 'Online',
    overallStatus: 'Ready',
    checklists: {
      examSet: true,
      deviceOn: true,
      facultyPresent: true,
      beaconDetected: true,
      noAlerts: true,
    },
    notes: 'Standard exam setup. Desks numbered 1-40.',
  },
  {
    id: 'h-2',
    hall: 'A1-02',
    block: 'A1',
    floor: '01',
    capacity: 40,
    currentExam: 'Physics',
    faculty: 'Ms. Sarah Khan',
    beaconId: 'B-1088',
    beaconStatus: 'Detected',
    deviceStatus: 'Online',
    overallStatus: 'Ready',
    checklists: {
      examSet: true,
      deviceOn: true,
      facultyPresent: true,
      beaconDetected: true,
      noAlerts: true,
    },
    notes: 'Formula sheets pre-placed on desks.',
  },
  {
    id: 'h-3',
    hall: 'A1-03',
    block: 'A1',
    floor: '01',
    capacity: 45,
    currentExam: 'Chemistry',
    faculty: 'Mr. Ravi Patel',
    beaconId: 'B-1090',
    beaconStatus: 'Weak Signal',
    deviceStatus: 'Online',
    overallStatus: 'Problem',
    checklists: {
      examSet: true,
      deviceOn: true,
      facultyPresent: false,
      beaconDetected: false,
      noAlerts: false,
    },
    notes: 'Faculty beacon reporting weak signal outside entrance. Reliever alerted.',
  },
  {
    id: 'h-4',
    hall: 'A1-04',
    block: 'A1',
    floor: '01',
    capacity: 35,
    currentExam: 'Biology',
    faculty: 'Ms. Emily Green',
    beaconId: 'B-2011',
    beaconStatus: 'Not Detected',
    deviceStatus: 'Offline',
    overallStatus: 'Problem',
    checklists: {
      examSet: true,
      deviceOn: false,
      facultyPresent: false,
      beaconDetected: false,
      noAlerts: false,
    },
    notes: 'BLE Hub offline and invigilator unlocated. Requires immediate intervention.',
  },
  {
    id: 'h-5',
    hall: 'B2-02',
    block: 'B2',
    floor: '02',
    capacity: 50,
    currentExam: 'History',
    faculty: 'Mr. Ahmed Ali',
    beaconId: 'B-2055',
    beaconStatus: 'Detected',
    deviceStatus: 'Online',
    overallStatus: 'Ready',
    checklists: {
      examSet: true,
      deviceOn: true,
      facultyPresent: true,
      beaconDetected: true,
      noAlerts: true,
    },
    notes: 'Room verified. Extra answer scripts stocked.',
  },
  {
    id: 'h-6',
    hall: 'B2-03',
    block: 'B2',
    floor: '02',
    capacity: 50,
    currentExam: 'English',
    faculty: 'Ms. Aisha Rahman',
    beaconId: 'B-2089',
    beaconStatus: 'Detected',
    deviceStatus: 'Online',
    overallStatus: 'Ready',
    checklists: {
      examSet: true,
      deviceOn: true,
      facultyPresent: true,
      beaconDetected: true,
      noAlerts: true,
    },
    notes: 'Ready for 10-minute pre-reading interval.',
  },
];

export const INITIAL_STAFF: StaffMember[] = [
  {
    id: 'st-1',
    name: 'Mr. James Lewis',
    initials: 'JL',
    staffId: 'ST-001',
    role: 'Hall Invigilator',
    department: 'Mathematics',
    designation: 'Senior Lecturer',
    email: 'j.lewis@college.edu',
    phone: '+1 (555) 014-2201',
    accountStatus: 'Active',
    beaconId: 'B-1042',
    beaconStatus: 'Detected',
    signalStrength: '-62 dBm (Good)',
    lastDetected: 'Just now',
    checkedInTime: '08:45',
    status: 'Checked In',
    assignedHall: 'A1-01',
    block: 'A1',
    floor: '01',
    assignedDeviceId: 'INV-0012',
  },
  {
    id: 'st-2',
    name: 'Ms. Sarah Khan',
    initials: 'SK',
    staffId: 'ST-002',
    role: 'Hall Invigilator',
    department: 'Physics',
    designation: 'Assistant Professor',
    email: 's.khan@college.edu',
    phone: '+1 (555) 018-9942',
    accountStatus: 'Active',
    beaconId: 'B-1088',
    beaconStatus: 'Detected',
    signalStrength: '-58 dBm (Good)',
    lastDetected: '1 min ago',
    checkedInTime: '08:40',
    status: 'Checked In',
    assignedHall: 'A1-02',
    block: 'A1',
    floor: '01',
    assignedDeviceId: 'INV-0018',
  },
  {
    id: 'st-3',
    name: 'Mr. Ravi Patel',
    initials: 'RP',
    staffId: 'ST-003',
    role: 'Hall Invigilator',
    department: 'Chemistry',
    designation: 'Associate Professor',
    email: 'r.patel@college.edu',
    phone: '+1 (555) 019-3382',
    accountStatus: 'Active',
    beaconId: 'B-1090',
    beaconStatus: 'Weak Signal',
    signalStrength: '-84 dBm (Weak)',
    lastDetected: '8 mins ago',
    checkedInTime: '09:15',
    status: 'Late',
    assignedHall: 'A1-03',
    block: 'A1',
    floor: '01',
    assignedDeviceId: 'INV-0021',
  },
  {
    id: 'st-4',
    name: 'Ms. Emily Green',
    initials: 'EG',
    staffId: 'ST-004',
    role: 'Hall Invigilator',
    department: 'Biology',
    designation: 'Assistant Professor',
    email: 'e.green@college.edu',
    phone: '+1 (555) 012-7711',
    accountStatus: 'Active',
    beaconId: 'B-2011',
    beaconStatus: 'Not Detected',
    signalStrength: 'None (Out of Range)',
    lastDetected: 'Never',
    checkedInTime: undefined,
    status: 'Absent',
    assignedHall: 'A1-04',
    block: 'A1',
    floor: '01',
    assignedDeviceId: 'INV-0024',
  },
  {
    id: 'st-5',
    name: 'Mr. Ahmed Ali',
    initials: 'AA',
    staffId: 'ST-005',
    role: 'Reliever',
    department: 'History',
    designation: 'Lecturer',
    email: 'a.ali@college.edu',
    phone: '+1 (555) 017-4402',
    accountStatus: 'Active',
    beaconId: 'B-2055',
    beaconStatus: 'Detected',
    signalStrength: '-52 dBm (Good)',
    lastDetected: 'Just now',
    checkedInTime: '08:50',
    status: 'Checked In',
    assignedHall: 'B2-02',
    block: 'B2',
    floor: '02',
    assignedDeviceId: 'INV-0027',
  },
  {
    id: 'st-6',
    name: 'Ms. Aisha Rahman',
    initials: 'AR',
    staffId: 'ST-006',
    role: 'Hall Invigilator',
    department: 'Computer Science',
    designation: 'Associate Professor',
    email: 'a.rahman@college.edu',
    phone: '+1 (555) 013-8829',
    accountStatus: 'Active',
    beaconId: 'B-2089',
    beaconStatus: 'Detected',
    signalStrength: '-60 dBm (Good)',
    lastDetected: 'Just now',
    checkedInTime: '08:35',
    status: 'Checked In',
    assignedHall: 'B2-03',
    block: 'B2',
    floor: '02',
    assignedDeviceId: 'INV-0030',
  },
  {
    id: 'st-7',
    name: 'Mr. Marcus Vance',
    initials: 'MV',
    staffId: 'ST-007',
    role: 'Flying Squad',
    department: 'Mathematics',
    designation: 'Senior Faculty',
    email: 'm.vance@college.edu',
    phone: '+1 (555) 016-5510',
    accountStatus: 'Active',
    beaconId: 'B-3012',
    beaconStatus: 'Detected',
    signalStrength: '-65 dBm (Good)',
    lastDetected: '3 mins ago',
    checkedInTime: '08:30',
    status: 'On Duty',
    assignedHall: 'Floating (Campus-Wide)',
    block: 'Main',
    floor: 'All',
    assignedDeviceId: 'INV-0035',
  },
];

export const INITIAL_DEVICES: Device[] = [
  {
    id: 'dev-1',
    deviceId: 'INV-0012',
    hall: 'A1-01',
    block: 'A1',
    floor: '1',
    beaconId: 'B-1042',
    beaconStatus: 'Detected',
    signalStrength: '-62 dBm (Good)',
    batteryLevel: 94,
    lastPing: '12s ago',
    status: 'Online',
    ipAddress: '192.168.1.101',
    firmwareVersion: 'v2.4.1',
    assignedFaculty: 'Mr. James Lewis',
  },
  {
    id: 'dev-2',
    deviceId: 'INV-0018',
    hall: 'A1-02',
    block: 'A1',
    floor: '1',
    beaconId: 'B-1088',
    beaconStatus: 'Detected',
    signalStrength: '-58 dBm (Good)',
    batteryLevel: 87,
    lastPing: '45s ago',
    status: 'Online',
    ipAddress: '192.168.1.102',
    firmwareVersion: 'v2.4.1',
    assignedFaculty: 'Ms. Sarah Khan',
  },
  {
    id: 'dev-3',
    deviceId: 'INV-0021',
    hall: 'A1-03',
    block: 'A1',
    floor: '1',
    beaconId: 'B-1090',
    beaconStatus: 'Weak Signal',
    signalStrength: '-84 dBm (Weak)',
    batteryLevel: 62,
    lastPing: '2m ago',
    status: 'Warning',
    ipAddress: '192.168.1.103',
    firmwareVersion: 'v2.4.0',
    assignedFaculty: 'Mr. Ravi Patel',
  },
  {
    id: 'dev-4',
    deviceId: 'INV-0024',
    hall: 'A1-04',
    block: 'A1',
    floor: '1',
    beaconId: 'B-2011',
    beaconStatus: 'Not Detected',
    signalStrength: 'None (Offline)',
    batteryLevel: 12,
    lastPing: '18m ago',
    status: 'Offline',
    ipAddress: '192.168.1.104',
    firmwareVersion: 'v2.3.9',
    assignedFaculty: 'Ms. Emily Green',
  },
  {
    id: 'dev-5',
    deviceId: 'INV-0027',
    hall: 'B2-02',
    block: 'B2',
    floor: '2',
    beaconId: 'B-2055',
    beaconStatus: 'Detected',
    signalStrength: '-52 dBm (Good)',
    batteryLevel: 98,
    lastPing: '5s ago',
    status: 'Online',
    ipAddress: '192.168.1.105',
    firmwareVersion: 'v2.4.1',
    assignedFaculty: 'Mr. Ahmed Ali',
  },
  {
    id: 'dev-6',
    deviceId: 'INV-0030',
    hall: 'B2-03',
    block: 'B2',
    floor: '2',
    beaconId: 'B-2089',
    beaconStatus: 'Detected',
    signalStrength: '-60 dBm (Good)',
    batteryLevel: 91,
    lastPing: '20s ago',
    status: 'Online',
    ipAddress: '192.168.1.106',
    firmwareVersion: 'v2.4.1',
    assignedFaculty: 'Ms. Aisha Rahman',
  },
];

export const INITIAL_PROBLEMS: ProblemIncident[] = [
  {
    id: 'prob-1',
    hall: 'A1-03',
    examCode: 'CHEM-205',
    category: 'Staff Delay',
    description: 'Faculty beacon outside range. Reliever alerted and standby invigilator assigned.',
    severity: 'Medium',
    reportedAt: '08:52 AM',
    reportedBy: 'ESP32 Automation Hub',
    status: 'Investigating',
  },
  {
    id: 'prob-2',
    hall: 'A1-04',
    examCode: 'BIO-101',
    category: 'Device Fault',
    description: 'Hall hub offline. Invigilator replaced with Flying Squad member.',
    severity: 'High',
    reportedAt: '08:45 AM',
    reportedBy: 'ESP32 Automation Hub',
    status: 'Open',
  },
];
